import Head from "next/head";

import { Box, Button } from "@chakra-ui/react";
import PageLoader from "@/components/PageLoader";

export default function Home() {
  return (
    <>
      <Head>
        <title>GreenspaceDAO</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icons/favicon.ico" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/icons/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/icons/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/icons/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest"></link>
      </Head>
      <PageLoader isLoading>
        <Box
          as="main"
          bgRepeat={"no-repeat"}
          bgGradient={"linear(-130deg,gs-green.700,black 60%)"}
          h={"100vh"}
          pos={"relative"}
        >
          <Button layerStyle={"with-shadow"}>Join the waitlist</Button>
          <Box
            h={"full"}
            bg={"rgba(41, 41, 41,0.40)"}
            backdropFilter={"blur(30px)"}
          ></Box>
        </Box>
      </PageLoader>
    </>
  );
}
